baseurl: 'https://adamhaile.com'
languageCode: en-us
title: Adam Haile
theme: hugo-freelancer-theme
canonifyURLS: true
enableRobotsTXT: true
permalinks:
  posts: '/:year/:month/:day/:slug/'
  code: '/:slug/'
params:
  name: Adam Haile
  description: My awesome description
  email: adammhaile@gmail.com
  custom_css: ["main.css"]
  custom_js: []
  navigation:
    brand: Adam Haile's Portfolio
  header:
    image: profile.png
    name: Adam Haile
    subtitle: Maker - Engineer - Artist
  portfolio:
    title: Portfolio
    modal:
      client: Client
      date: Date
      category: Category
      buttontext: Close
  about:
    title: About
    left: >-
      Freelancer is a free bootstrap theme created by Start Bootstrap. The
      download includes the complete source files including HTML, CSS, and
      JavaScript as well as optional LESS stylesheets for easy customization.
    right: >-
      Whether you're a student looking to showcase your work, a professional
      looking to attract clients, or a graphic artist looking to share your
      projects, this template is the perfect starting point!
    button:
      text: Download theme
      link: //github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip
      icon: download
  contact:
    title: Contact
    form:
      name:
        text: Name
        error: Please enter your name.
      email:
        text: Email Address
        error: Please enter your email address.
      phone:
        text: Phone Number
        error: Please enter your phone number.
      message:
        text: Message
        error: Please enter a message.
      button:
        text: Send
  footer:
    copyright: 'Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io).'
    location:
      title: Location
      address:
        - 3481 Melrose Place
        - 'Beverly Hills, CA 90210'
    social:
      title: Around the web
      networks:
        - icon: fa-github
          link: //github.com/spf13/hugo
        - icon: fa-stack-overflow
          link: //stackoverflow.com/questions/tagged/hugo
    credits:
      title: About Freelancer
      text: >-
        Freelance is a free to use, open source Bootstrap theme created by
        [Start Bootstrap](//startbootstrap.com).
