baseurl: 'https://adamhaile.com/'
languageCode: en-us
title: Adam Haile
theme: hugo-freelancer-theme
canonifyURLS: true
enableRobotsTXT: true
permalinks:
  posts: '/:year/:month/:day/:slug/'
  code: '/:slug/'
params:
  name: Adam Haile
  description: Maker - Engineer - Artist
  email: adammhaile@gmail.com
  custom_css: ["main.css"]
  custom_js: []
  navigation:
    brand: Adam Haile's Portfolio
  header:
    image: profile.jpg
    name: Adam Haile
    subtitle: Maker - Engineer - Artist
  portfolio:
    title: Portfolio
    modal:
      client: Client
      date: Date
      category: Category
      buttontext: Close
  about:
    title: About
    left: >-
      I am a software engineer at Red Hat by day but, the rest of the time
      I am a "Maker" as it's generally put these days. I'm probably most
      known for my work with LED displays and the open source hardware
      I've helped create to build those displays. But I don't draw the line
      there and the things I make really depend on my mood at the time.
      Some might call it art, others may not, and that's ok.
      I'm heavily interested in digital fabrication techniques and how I
      can use them to enable my own creativity. So I'm well versed in CAD,
      3D printing, laser cutting, and CNC machining.
    right: >-
      This portfolio mostly exists to show of my larger and flashier projects and
      serves as quick access to much of the work I've done either by myself or
      as part of Maniacal Labs, an open source hardware company I run with Dan Ternes.
      Much more can be seen over at [ManiacalLabs.com](https://maniacallabs.com).
      Most of what I build is created for my own enjoyment, but I'm open to
      commisions. Contact form below.

    # button:
    #   text: Download theme
    #   link: //github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip
    #   icon: download
  contact:
    title: Contact
    form:
      name:
        text: Name
        error: Please enter your name.
      email:
        text: Email Address
        error: Please enter your email address.
      message:
        text: Message
        error: Please enter a message.
      button:
        text: Send
  footer:
    copyright: 'Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io).'
    # location:
    #   title: Location
    #   address:
    #     - Raleigh, NC
    social:
      title: Around the web
      networks:
        - icon: fa-github
          link: //github.com/adammhaile
        - icon: fa-github
          link: //github.com/ManiacalLabs
        - icon: fa-twitter
          link: //twitter.com/ManiacalLabs
    # credits:
    #   title: About Freelancer
    #   text: >-
    #     Freelance is a free to use, open source Bootstrap theme created by
    #     [Start Bootstrap](//startbootstrap.com).
